---
apiVersion: v1
kind: Service
metadata:
  namespace: blogt
  name: blogt-api
spec:
  selector:
    app: blogt-api
  ports:
    - protocol: TCP
      port: 3000
      name: http
  type: LoadBalancer
  externalTrafficPolicy: Local 